# Generated by Django 4.2 on 2023-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_url', models.TextField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
