# Generated by Django 4.2 on 2023-04-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='ProductosModel',
        ),
        migrations.AlterModelTable(
            name='productosmodel',
            table='productos',
        ),
    ]
